server:
  port: 9080
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: test-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"   # Imports configuration data from a config server when available
  cloud:
    config:
      uri: http://localhost:8071
      request-connect-timeout: 5000   # Timeout on waiting to connect to the config server (ms)
      request-read-timeout: 5000      # Timeout on waiting to read configuration data from the config server (ms)
      fail-fast: true                 # In production, set to true. Makes a failure to connect to the config server fatal
      retry:
        max-attempts: 6
        initial-interval: 1000        # Initial retry interval for backoff (ms)
        max-interval: 2000            # Maximum retry interval for backoff (ms)
        multiplier: 1.1               # Multiplier to compute the next interval
  profiles:
    active: kubernetes
  security:
    oauth2:
      client:
        registration:
          test-service-credentials:
            provider: spring
            client-id: test-service
            client-secret: test-service-secret
            authorization-grant-type: client_credentials
            scope: iam.facultad
            client-name: test-service-credentials
        provider:
          spring:
            issuer-uri: http://auth:9000
        rest:
          client-id: test-service-credentials
      resourceserver:
        jwt:
          issuer-uri: http://auth:9000

security:
  clientId: test-service      # Needed by the AuthServerUserLookupService class

management:
  endpoints:
    web:
      exposure:
        include: refresh
